version: '2'

services:
  aeond:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BRANCH: v0.12.8.0-aeon
    command: --data-dir /aeon --non-interactive
    volumes:
      # /aeon in container should eventually contain the lmdb folder
      - <path_to_contents_of_lmdb>:/aeon
    ports:
      - "11180:11180"
      - "11181:11181"
    environment:
      - USER_ID=1000
      - P2P_BIND_IP=0.0.0.0
      - P2P_BIND_PORT=11180
      - LOG_LEVEL=0
      - RPC_BIND_IP=0.0.0.0
      - RPC_BIND_PORT=11181
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
