#!/bin/bash

MOST_RECENT_TAG=$(curl -s https://api.github.com/repos/aeonix/aeon/tags | grep -i name | awk 'NR==1{print $2}' | tr -d "\",")
if [ "$MOST_RECENT_TAG" = "$DOCKER_TAG" ]; then
  docker tag $IMAGE_NAME $DOCKER_REPO:most_recent_tag
  docker push $DOCKER_REPO:most_recent_tag
fi
